[package]
name = "coinche"
version = "0.1.0"
authors = ["Thomas BESSOU <thomas.bessou@hotmail.fr>"]
edition = "2018"
publish = false

[profile]
# Preserve line numbers in release
release = { debug = 1 }

[dependencies]
ws = "0.9.1"
failure = "0.1.6"
serde = "1.0.101"
serde_derive = "1.0.101"
serde_json = "1.0.41"
derive_deref = "1.1.0"
rand = "0.7.2"
