[package]
name = "coinche"
version = "0.1.0"
authors = ["Thomas BESSOU <thomas.bessou@hotmail.fr>"]
edition = "2018"
publish = false

[profile]
# Preserve line numbers in release
release = { debug = 1 }

[dependencies]
actix-web = "1.0.8"
actix-files = "0.1.6"
actix-rt = "0.2.5"
ctrlc = "3.1.3"
ws = "0.9.1"
failure = "0.1.6"
futures = "0.1.29"
serde = "1.0.101"
serde_derive = "1.0.101"
serde_json = "1.0.41"
derive_deref = "1.1.0"
rand = "0.7.2"
